# Generated by Django 4.0.2 on 2022-02-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=200)),
                ('notice_description', models.TextField()),
                ('notice_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
