# Generated by Django 4.0.2 on 2022-02-25 09:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=200)),
                ('doctor_facebook_link', models.CharField(max_length=200, null=True)),
                ('doctor_instagram_link', models.CharField(max_length=200, null=True)),
                ('doctor_linkedin_link', models.CharField(max_length=200, null=True)),
                ('doctor_twitter_link', models.CharField(max_length=200, null=True)),
                ('doctor_image', models.FileField(upload_to='static/uploads')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.category')),
            ],
        ),
    ]
